config/routes.rb
Rails.application.routes.draw do

  root 'snippets#welcome'

  resources :snippets do
    resources :comments
  end

  resources :tables, only: [:index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :snippet
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  has_many :comments
  validates :kind, presence: true
  validates :title,  presence: true
  validates :work,  presence: true


  def self.search(query)
    where("kind ILIKE ? OR title ILIKE ? OR work ILIKE ?",
            "%#{query}%", "%#{query}%", "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @snippet = Snippet.find(params[:snippet_id])
    comment = Comment.new(text: params[:comment][:text])
    comment.snippet = @snippet
    comment.save

    redirect_to snippet_path(@snippet)

  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def welcome
    @num_ruby_snippets = Snippet.where(kind: "ruby").count
    @num_html_snippets = Snippet.where(kind: "html").count
    @num_css_snippets = Snippet.where(kind: "css").count
    @num_javascript_snippets = Snippet.where(kind: "javascript").count
  end


  def index
    @snippets = Snippet.where(kind: params[:kind])
  end

  def show
    @snippet=Snippet.find params[:id]
    @comment=Comment.new
  end

  def new
    @snippet=Snippet.new
  end

  def create
    snippet_params = params.require(:snippet).permit(:kind, :title, :work)
    @snippet = Snippet.new(snippet_params)

      if @snippet.save
        redirect_to snippet_path(@snippet)
      else
        render :new
      end
  end

  def edit
    @snippet = Snippet.find (params[:id])
  end

  def update
    @snippet = Snippet.find(params[:id])
    @snippet.update(snippet_params)
    redirect_to tables_path
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    redirect_to tables_path
  end


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def index
    @snippets = Snippet.all
    @snippets = @snippets.search(params[:q])
    @total_snippets = @snippets.length
    @snippets = @snippets.page(params[:page]).per(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap's Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <h1>Code Snippets</h1>
    <%= link_to "Home", root_path %>
    |
    <%= link_to "All Snippets", tables_path %>
    |
  </div>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>
  <div class="form-group">
    <%= f.label :kind %>
    <%= f.select :kind, [['Ruby','ruby'],['HTML','html'],['CSS','css'],['JavasScript','javascript']] %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
  <%= f.label :work %>
  <%= f.text_area :work, :cols => 30, :rows => 10 %>
  </div>
  <div class="form-group">
  <%= f.submit "Save" %>
</div>
<% end %>

app/views/snippets/edit.html.erb
<div class="container">
<h2>Edit this Snippet</h2>


<%= render partial: "snippets/form" %>

</div>

app/views/snippets/index.html.erb
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Kind</th>
        <th>Title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @snippets.each do |snippet| %>
        <tr>
          <td><%= snippet.kind %></td>
          <td><%= snippet.title %></td>
          <td><%= link_to "View", snippet_path(snippet) %></td>
          <td><%= button_to "Edit", edit_snippet_path(snippet), method: :get %></td>
          <td><%= button_to "Delete", snippet_path(snippet), method: :delete,
                    data: {confirm: "Are you sure you want to delete this snippet?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/snippets/new.html.erb
<div class="container">
<h2>Add a new Snippet</h2>


<%= render partial: "snippets/form" %>

</div>

app/views/snippets/show.html.erb
<div class="container">

<h2>Snippet details(<% Snippet.find params[:id] %>)</h2>

<p>Kind: <%= @snippet.kind %></p>
<p>Title: <%= @snippet.title %></p>
<p>Work: <%= @snippet.work %></p>

</div>

<% @snippet.comments.each do |comment| %>
<div>
  <%= comment.text %>
</div>

<% end %>

<%= form_for [@snippet, @comment] do |f| %>
  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <%= f.submit %>
<% end %>

app/views/snippets/welcome.html.erb
<%= link_to "Ruby (#{@num_ruby_snippets} Snippets)", snippets_path(kind: "ruby") %><br />
<%= link_to "HTML (#{@num_html_snippets} Snippets)", snippets_path(kind: "html") %><br />
<%= link_to "CSS (#{@num_css_snippets} Snippets)", snippets_path(kind: "css") %><br />
<%= link_to "JavasScript (#{@num_javascript_snippets} Snippets)", snippets_path(kind: "javascript") %><br />

app/views/tables/index.html.erb
<div class="container">

<h2>All Snippets (<%= @total_snippets %>)</h2>

<%= form_tag tables_path, method: :get do %>
  <%= label_tag :q, "Search" %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<br>
<%= link_to "Add a New Snippet", new_snippet_path %>
<br>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Kind</th>
        <th>Title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @snippets.each do |snippet| %>
        <tr>
          <td><%= snippet.kind %></td>
          <td><%= snippet.title %></td>
          <td><%= link_to "View", snippet_path(snippet) %></td>
          <td><%= button_to "Edit", edit_snippet_path(snippet), method: :get %></td>
          <td><%= button_to "Delete", snippet_path(snippet), method: :delete,
                    data: {confirm: "Are you sure you want to delete this snippet?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @snippets, q: params[:q] %>
</div>